//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNongsan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Add_magiamgia_donhang
    {
        public int id_mgg_donhang { get; set; }
        public string madonhang { get; set; }
        public Nullable<int> giamgia { get; set; }
    }
}
