//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNongsan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Danhgianguoidung
    {
        public int id_danhgia { get; set; }
        public Nullable<int> id_nguoidung { get; set; }
        public Nullable<int> id_sanpham { get; set; }
        public Nullable<int> sao_danhgia { get; set; }
        public string noidung { get; set; }
    
        public virtual Nguoidung Nguoidung { get; set; }
    }
}
