//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNongsan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magiamgia
    {
        public int id_magiamgia { get; set; }
        public string magiamgia1 { get; set; }
        public Nullable<int> dongia { get; set; }
        public string tenmagiamgia { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<int> trangthai { get; set; }
    }
}
