//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNongsan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhantin
    {
        public int id_tinnhan { get; set; }
        public Nullable<int> id_admin { get; set; }
        public Nullable<int> id_khachhang { get; set; }
        public string noidungnhan { get; set; }
        public Nullable<System.DateTime> thoigiannhan { get; set; }
        public Nullable<int> trangthai { get; set; }
    }
}
