//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNongsan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanpham
    {
        public int id_sanpham { get; set; }
        public Nullable<int> id_danhmuc { get; set; }
        public string tensanpham { get; set; }
        public Nullable<int> giatien { get; set; }
        public string img_sanpham { get; set; }
        public string list_img { get; set; }
        public string mota { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<int> soluotmua { get; set; }
        public Nullable<System.DateTime> ngay_them { get; set; }
        public Nullable<int> trangthai { get; set; }
    
        public virtual DanhmucSanpham DanhmucSanpham { get; set; }
    }
}
